---
keep_only_specified: False

nginx_conf_dir: "/etc/nginx"
nginx_service_name: "nginx"

nginx_official_repo_mainline: False

nginx_user: "{% if ansible_os_family == 'RedHat' or ansible_os_family == 'Suse' %}nginx{% elif ansible_os_family == 'Debian' %}www-data{% elif ansible_os_family == 'FreeBSD' %}www{% endif %}"
nginx_group: "{{nginx_user}}"

nginx_pid_file: '/var/run/{{nginx_service_name}}.pid'

nginx_worker_processes: "{% if ansible_processor_vcpus is defined %}{{ ansible_processor_vcpus }}{% else %}auto{% endif %}"
nginx_worker_rlimit_nofile: 1024
nginx_log_dir: "/var/log/nginx"
nginx_error_log_level: "error"

nginx_extra_root_params: []
nginx_events_params:
  - worker_connections {% if nginx_max_clients is defined %}{{nginx_max_clients}}{% else %}512{% endif %}
  - multi_accept on
  - use epoll

nginx_http_params: "{{ nginx_http_default_params }}"

nginx_stream_params: []

nginx_sites:
  default:
   - listen 80 default_server
   - server_name _
   - root "{% if ansible_os_family == 'FreeBSD' %}/usr/local/www/nginx-dist{% else %}/usr/share/nginx/html{% endif %}"
   - index index.html
nginx_remove_sites: []

nginx_configs:
  upstream:
    - upstream php-upstream { server localhost:9000; }
  gzip:
    - gzip on
    - gzip_disable msie6
    - gzip_vary on
    - gzip_proxied any
    - gzip_comp_level 6
    - gzip_buffers 16 8k
    - gzip_http_version 1.1
    - gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript

nginx_stream_configs: {}
nginx_remove_configs: []

nginx_auth_basic_files: {}
nginx_remove_auth_basic_files: []

nginx_daemon_mode: "on"
