---
- include: ensure-dirs.yml
  tags: [configuration,nginx]

- include: remove-defaults.yml
  when: not keep_only_specified
  tags: [configuration,nginx]

- include: remove-extras.yml
  when: keep_only_specified
  tags: [configuration,nginx]

- include: remove-unwanted.yml
  tags: [configuration,nginx]

- include: configuration.yml
  tags: [configuration,nginx]
